//Auth

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const REGISTER_SUCCESS= 'REGISTER_SUCCESS'
export const PERSIST_PROFILE = 'PERSIST_PROFILE'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGOUT = 'LOGOUT'

// App

export const PERSIST_COMM_PROFILES = 'PERSIST_COMM_PROFILES'
export const PERSIST_CHOSEN_PROFILE = 'PERSIST_CHOSEN_PROFILE'
export const PERSIST_CHOSEN_PROFILE_RATINGS = 'PERSIST_CHOSEN_PROFILE_RATINGS'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'


export const FILTER_PRO_LOC = 'FILTER_PRO_LOC'
export const FILTER_PRO_GEN = 'FILTER_PRO_GEN'
export const FILTER_PRO_LANG = 'FILTER_PRO_LANG'
export const FILTER_PRO_AGE = 'FILTER_PRO_AGE'
export const CLEAR_FILTER_PRO = 'CLEAR_FILTER_PRO'

export const PERSIST_RECOMMANDATIONS = 'PERSIST_RECOMMANDATIONS'
export const FILTER_REC_THEME = 'FILTER_REC_THEME'
export const FILTER_REC_LOC = 'FILTER_REC_LOC'
export const FILTER_REC_ALL = 'FILTER_REC_ALL'
export const CLEAR_FILTER_REC = 'CLEAR_FILTER_REC'

export const PERSIST_QUESTIONS = 'PERSIST_QUESTIONS'
export const FILTER_QUE_THEME = 'FILTER_QUE_THEME'
export const FILTER_QUE_LOC = 'FILTER_QUE_LOC'
export const FILTER_QUE_ALL = 'FILTER_QUE_ALL'
export const CLEAR_FILTER_QUE = 'CLEAR_FILTER_QUE'

export const PERSIST_USER_MEETINGS = 'PERSIST_USER_MEETINGS'
export const REQUEST_MEETING = 'REQUEST_MEETING'


export const PERSIST_CITIES = 'PERSIST_CITIES'